---
# Remove EXTERNALLY-MANAGED if pip_externally_managed is true and python3 version is 3.11 or higher.
# Related issue: https://github.com/geerlingguy/ansible-role-pip/issues/57
- name: Ensure "{{ 'absent' if not pip_externally_managed else 'present' }}" of EXTERNALLY-MANAGED's Python base environments
  vars:
    python_version: "{{ ansible_facts.python_version }}"
    python_version_short: "{{ ansible_facts.python.version.major }}.{{ ansible_facts.python.version.minor }}"
  ansible.builtin.file:
    path: "/usr/lib/python{{ python_version_short }}/EXTERNALLY-MANAGED"
    state: "{{ 'absent' if not pip_externally_managed else 'touch' }}"
  when: python_version is defined and python_version is version_compare('3.11', '>=')

- name: Ensure Pip is installed.
  package:
    name: "{{ pip_package }}"
    state: present

- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    extra_args: "{{ item.extra_args | default(omit) }}"
    executable: "{{ item.virtualenv | default(false) | ternary(omit, pip_executable) }}"
  loop: "{{ pip_install_packages }}"
